.PHONY: all build

all: build

build:
	@docker stop dev-peer0.org1.example.com-tuna-app-1.0
	@docker rm dev-peer0.org1.example.com-tuna-app-1.0
	@docker rmi dev-peer0.org1.example.com-tuna-app-1.0 -f
